---
- hosts: HaProxy
  connection: local
#initialisation des variables 

  #VARIABLES 
  vars_files: 
   - variables/haproxy/var_haproxy.yaml


  remote_user: azureuser


  tasks:
    - name: verif HaProxy a jour et demarre
      apt: name=haproxy state=latest
    - name: start haproxy
      service:
          name: haproxy
          state: started

    - name: ecriture du fichier de configuration haproxy.cfg
      template:
          src: templates/haproxy/haproxy.cfg
          dest: /etc/haproxy/haproxy.cfg
      become: yes
    - name: restart haproxy
      service:
          name: haproxy
          state: restarted
      become: yes

