---
- hosts: Shinken
  # connection: local
  #initialisation des variables 
  become: yes
  remote_user: azureuser

  #VARIABLES 
  vars_files: 
   - variables/shinken/var_shinken.yaml

# CONFIGURATION DES FICHIERS 
   - name: Creation des fichiers hostgroup
     file:
      path: "/etc/shinken/hostgroups/_{{ item }}.cfg"
      owner: shinken
      group: shinken
      mode: 0644
      state: touch
     loop: "{{ hostgroup }}"  


   - name: Configuration des hostgroups
     blockinfile:
       path: "/etc/shinken/hostgroups/_{{ item }}.cfg"
       block: |
         define hostgroup {
           hostgroup_name  {{ item }}
           alias           {{ item }}
         }
     loop: "{{ hostgroup }}"



# CONFIGURATION DES SERVICES

     #   - name: config services
     #     template:
     #  src: templates/shinken/services/services.cfg
     #  dest: /etc/shinken/services/services.cfg

# CONFIGURATION DES MACHINES

   - name: Création des fichiers hosts
     file:
       path: "/etc/shinken/hosts/_{{ item }}.cfg"
       owner: shinken
       group: shinken
       mode: 0644
       state: touch
     loop: "{{ hosts }}"


   - name: Configuration des hosts
     blockinfile:
       path: "/etc/shinken/hosts/_{{ item }}.cfg"
       block: |
        define host{
           use                 generic-host
           contact_groups      {{ item.contact_groups }}
           host_name           {{ item.host_name }}
           address             {{ item.address }}
           hostgroup           {{ item.hostgroup }}
        }
     loop: "{{ hosts }}"
