---
- hosts: Shinken
  # connection: local
#initialisation des variables 
  become: yes

  #VARIABLES 
  vars_files: 
   - var_shinken.yaml

  remote_user: azureuser
  
# CONFIGURATION DES GROUPES DE MACHINE
    - name: Creation des fichiers hostgroup
      file:
        path: "/etc/shinken/hostgroups/{{ item }}.cfg"
        owner: shinken
        group: shinken
        mode: 0644
        state: touch
      loop: "{{ hostgroup }}"  


    - name: Configuration des hostgroups
      blockinfile:
        path: "/etc/shinken/hostgroups/{{ item }}.cfg"
        block: |
          define hostgroup {
            hostgroup_name  {{ item }}
            alias           {{ item }}
          }
      loop: "{{ hostgroup }}"



# CONFIGURATION DES SERVICES

    - name: Configuration des services
      template:
          src: templates/shinken/services/services.cfg
          dest: /etc/shinken/services/services.cfg

# CONFIGURATION DES MACHINES

    - name: Création des fichiers hosts
      file:
        path: "/etc/shinken/hosts/_{{ item }}.cfg"
        owner: shinken
        group: shinken
        mode: 0644
        state: touch
      loop: "{{ hosts }}"


    - name: Configuration des hosts
      blockinfile:
        path: "/etc/shinken/hosts/_{{ item }}.cfg"
        block: |
         define host{
            use                 generic-host
            contact_groups      {{ item.contact_groups }}
            host_name           {{ item.host_name }}
            address             {{ item.address }}
            hostgroup           {{ item.hostgroup }}
         }
        loop: "{{ hosts }}"

